name: 发布最新版本&&部署文档

on:
  push:
    branches:
      - release

jobs:
  BUILDDOCS:
    runs-on: macOS-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@master
      - name: 初始化node环境
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - name: 安装项目依赖
        run: npm i
      - name: 开始编译部署
        run: npm run deploy:send text=正在部署新的zx-util-ui文档-请点击链接查看部署进度 title=CI部署DOCS通知 url=https://github.com/zx-js/zx-util-ui/actions node .robot/robot.js
      - name: 编译源码
        run: npm run build
      - name: 设置ssk
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACCESS_TOKEN" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "bhabgs@aliyun.com"
          git config --global user.name "bhabgs"

      - name: 编译部署文档
        run: |
          npm run deploy
      - name: 部署成功通知
        run: npm run deploy:send text=最新版本zx-util-ui文档体精部署成功请点击链接查看 title=CI部署DOCS通知 url=https://zx-js.github.io/zx-util-ui-docs/ node .robot/robot.js
      - name: 发布最新版本至npm
        run: npm publish
      - name: npm 最新版本部署成功通知
        run: npm run deploy:send text=最新版本zx-util-ui以部署至npm title=CINPM-publish通知 url=https://zx-js.github.io/zx-util-ui-docs/ node .robot/robot.js
