name: 文档发布

on:
  push:
    branches:
    - release

jobs:
  test:

    runs-on: macOS-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@master
    - name: 初始化node环境
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: 安装项目依赖
      run: npm i
    - name: 开始编译部署
      run: npm run deploy:to
    - name: 编译源码
      run: npm run build
    - name: 设置ssk
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
          mkdir -p ~/.ssh/
          echo "$ACCESS_TOKEN" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "bhabgs@aliyun.com"
          git config --global user.name "bhabgs"
        
    - name: 编译部署文档
      run: |
          npm run deploy
    - name: 部署成功通知
      run: npm run deploy:success
