name: 文档发布

on:
  push:
    branches:
    - release

jobs:
  BUILDDOCS:
    
    runs-on: macOS-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@master
    - name: 初始化node环境
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        INSTALL: npm install
        TODEPLOY: npm run deploy:to
        BUILD: npm run build
        BUILD_DOCS: npm run deploy
        DEPLOYSUCCESS: npm run deploy:success
        CI: true
